FROM python:3.11.2

ENV VENV=/venv
ENV PATH="$VENV/bin:$PATH"

COPY requirements.txt requirements.txt
RUN python -m venv $VENV && . venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

COPY /server/ /server/
COPY /proto/ /proto/
COPY /scripts/ /scripts/

RUN /scripts/build/gen_proto
RUN /scripts/build/patch_PyInquirer

ENTRYPOINT [ "/scripts/run_server" ]
CMD [ "/server/configs/default.json" ]
